What is PyTorch?
PyTorch is a Python-based scientific computing package serving two broad purposes:

A replacement for NumPy to use the power of GPUs and other accelerators.
An automatic differentiation library that is useful to implement neural networks.
PyTorch is an open source deep learning framework that makes it easy to develop machine learning models and deploy them to production. 

Import Torch

In [1]:
import torch

Create a few basic tensor manipulations

Create a 5x3 matrix filled with zeros and query it's datatype

In [2]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


Convert the Floats into the Int16

In [3]:
i = torch.ones((5,3),dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


As we can see the float was converted into int. We can use the manual seeding to initialize the learning weights randomly, ofter with a specific seed for the PRING for reproducibility of results: 

In [8]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
print(" A random tensor:")
print(r1)

r2 =torch.rand(2,2)
print('\nA different random tensor:')
print(r2) #new values

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print(r3) #repeates values of r1 because of re-seed

 A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


PyTorch tensors can perfrm arithmetic operations.Tensors of similar shape may be added, multiplied.etc.

In [7]:
ones = torch.ones(2,3)
print(ones)

twos = torch.ones(2,3) *2   #every element is multiplied by 2
print(twos)

threes = ones + twos         #addition allowed because the shaopes are similar       
print(threes)
print(threes.shape)

r1 = torch.rand(2,3)
r2 = torch.rand(2,3)
r3 = r1 +r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


Some additional mathematical operations in tensors

In [10]:
r = torch.rand(2,2) - 0.5* 2 #values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

#Common trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# Linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# Statistical and aggregage operations:
print('\nAverage and Standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[-0.7838, -0.0073],
        [-0.5872, -0.4062]])

Absolute value of r:
tensor([[0.7838, 0.0073],
        [0.5872, 0.4062]])

Inverse sine of r:
tensor([[-0.9007, -0.0073],
        [-0.6277, -0.4183]])

Determinant of r:
tensor(0.3141)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.7457, -0.6663],
        [-0.6663,  0.7457]]),
S=tensor([1.0140, 0.3097]),
V=tensor([[ 0.9622,  0.2723],
        [ 0.2723, -0.9622]]))

Average and Standard deviation of r:
(tensor(0.3307), tensor(-0.4461))

Maximum value of r:
tensor(-0.0073)
